## Promise 简介

Promise 通常被定义为**最终会变为可用值的代理**。

Promise 是一种处理异步代码（而不会陷入[回调地狱](http://callbackhell.com/)）的方式。





### Promise 如何运作

当 promise 被调用后，它会以**处理中状态**开始。 这意味着调用的函数会继续执行，而 promise 仍处于处理中直到解决为止，从而为调用的函数提供所请求的任何数据。

```js
let done = true
const isItDoneYet = new Promise((resolve, reject) => {  if (done) { 
    const workDone = '这是创建的东西'    
    resolve(workDone)  
} else {   
    const why = '仍然在处理其他事情'    reject(why)  
}})
```



### Promisifying技术

```js
const fs = require('fs')

const getFile = (fileName) => {
  return new Promise((resolve, reject) => {
    fs.readFile(fileName, (err, data) => {
      if (err) {
        reject(err)  // 调用 `reject` 会导致 promise 失败，无论是否传入错误作为参数，
        return        // 且不再进行下去。
      }
      resolve(data)
    })
  })
}

getFile('/etc/passwd')
.then(data => console.log(data))
.catch(err => console.error(err))
```

*在最新版本的 Node.js 中，无需为大多数 API 进行手动地转换。如果需要 promisifying 的函数具有正确的签名，则* [util 模块](http://nodejs.cn/api/util.html#util_util_promisify_original)*中有一个 promisifying 函数可以完成此操作。*



### 链式 promise

```js
const status = response => 
{  if (response.status >= 200 && response.status < 300) {    return Promise.resolve(response)  }  return Promise.reject(new Error(response.statusText))}
const json = response => response.json()
fetch('/todos.json')  .then(status)    // 注意，`status` 函数实际上在这里被调用，并且同样返回 promise，  .then(json)      // 这里唯一的区别是的 `json` 函数会返回解决时传入 `data` 的 promise，  .then(data => {  // 这是 `data` 会在此处作为匿名函数的第一个参数的原因。    console.log('请求成功获得 JSON 响应', data)  })  .catch(error => {    console.log('请求失败', error)  })
```

### 处理错误

当 promise 链中的任何内容失败并引发错误或拒绝 promise 时，则控制权会转到链中最近的 `catch()` 语句。

```js
new Promise((resolve, reject) => {  throw new Error('错误')}).catch(err => {  console.error(err)})
// 或
new Promise((resolve, reject) => {  reject('错误')}).catch(err => {  console.error(err)})
```

**级联错误**

如果在 `catch()` 内部引发错误，则可以附加第二个 `catch()`来处理，依此类推。

```js
new Promise((resolve, reject) => {
  throw new Error('错误')
})
  .catch(err => {
    throw new Error('错误')
  })
  .catch(err => {
    console.error(err)
  })
```



### 编排 promise

如果需要同步不同的 promise，则 `Promise.all()` 可以帮助定义 promise 列表，并在所有 promise 都被解决后执行一些操作。



```js
const f1 = fetch('/something.json')const f2 = fetch('/something2.json')
Promise.all([f1, f2]).then(res => {    
    console.log('结果的数组', res)  
}) .catch(err => {    console.error(err)  })
```

ES2015 解构赋值语法也可以执行：

```js
Promise.all([f1, f2]).then(([res1, res2]) => {
  console.log('结果', res1, res2)
})
```

#### `Promise.race()`

当传给其的首个 promise 被解决时，则 `Promise.race()` 开始运行，并且只运行一次附加的回调（传入第一个被解决的 promise 的结果）。

```js
const first = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, '第一个')
})
const second = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, '第二个')
})

Promise.race([first, second]).then(result => {
  console.log(result) // 第二个
})
```

## Async 和 Await 的现代异步

### 介绍

JavaScript 在很短的时间内从回调发展到了 promise（ES2015），且自 ES2017 以来，异步的 JavaScript 使用 async/await 语法甚至更加简单。

异步函数是 promise 和生成器的组合，基本上，它们是 promise 的更高级别的抽象。 而 async/await 建立在 promise 之上。

### 为什么引入 async/await

它们减少了 promises 的样板，且减少了 promise 链的“不破坏链条”的限制。



### 工作原理

```js
const doSomethingAsync = () => {
  return new Promise(resolve => {
    setTimeout(() => resolve('做些事情'), 3000)
  })
}
```



